'''
ctypes definitions and bindings for ANLTR3C

'''
import sys
from ctypes import *
# Discovery tool
from ctype_discovery import CTypeMapper

# Import autogenerated values. See genclib.py 
from generated.enums import *
from generated.fnmacros import *
from generated.functions import *
from generated.macros import *
from generated.structs import *
from generated.types import *
from generated.unions import *
from generated.values import *
from generated.variables import *


antlr_structs = dict(STRUCTS)
antlr_types = dict(TYPES)
antlr_unions = dict(UNIONS)


mapper = CTypeMapper(antlr_structs, antlr_types, antlr_unions)

ANTLR3_BASE_TREE_struct = mapper.discover_type('ANTLR3_BASE_TREE_struct')

#print ANTLR3_BASE_TREE_struct._fields_

