%
% function show_tree( string [, is_filename] )
%
% A mex file which interfaces to an ANTLR matlab grammar.  The
% function accepts a string and prints out a scheme-style AST.
%
% This is a direct traversal of the internal ANTLR parse tree, and
% isn't suitable for much except to debug the parse tree that's
% generated by the ANTLR grammar.
%
% If the "is_filename" flag is set (to anything) the string is
% interpreted as a filename and the contents of that file are
% parsed.
%
%
% Copyright(c) 2011 David Wingate
% 
% This file is part of the mparser package, which is licensed under
% the MIT license.  See the file COPYING for details.
%
